### ISSUE TITLE
option to select other languages

### ISSUE THREAD

**Issue by geryescalier** [mozilla-iot/mozilla-iot.github.io#18] opened 2018-02-15 02:19 UTC
**Goal**
The website has an option to select other languages

**Problem**
Currently in many countries it is not common to read or write in English and when accessing pages with information in English you lose interest in using that information

**Solution**
Allow choosing native language on the website

**Comment by kgiori** [comment] 2018-02-15 03:52
I like this idea.

Check out  http://snap4arduino.rocks/run as an example of a quality program with language support -- it is one of my faves. Click the settings menu (gear icon) and select "Language..." and any language that someone has translated the blocks and menus into will be listed. The project is 100% open source so should be feasible to look at that architecture. I also know the developers who built it in case we want to ask more questions.
![screen shot 2018-02-14 at 7 46 51 pm](https://user-images.githubusercontent.com/9487286/36239684-708e3678-11c0-11e8-9553-1282d2d8bb22.png)

**Comment by benfrancis** [comment] 2018-02-15 13:08
> Check out http://snap4arduino.rocks/run as an example of a quality program with language support -- it is one of my faves.

Note that this issue is about translating our website at iot.mozilla.org, not the gateway interface. I imagine Mozilla has existing mechanisms to deal with localised website content, we just need to find out what they are.

Localising the gateway UI is a separate, and trickier, issue.

**Comment by mikehenrty** [comment] 2018-02-16 10:59
Tools Suggestion: [Fluent](https://github.com/projectfluent/fluent.js) for your front-end library, and [Pontoon](https://pontoon.mozilla.org/) for your community translation tool.

We are going through the process of translating the website content for the [Common Voice project](https://github.com/mozilla/voice-web) right now, and I I highly recommend these two tools in conjunction. They are already quite feature rich, yet still in active development, and you can leverage Mozilla's existing l10n community.

**Comment by benfrancis** [comment] 2018-02-16 11:23
Thanks @mikehenrty !

**Comment by geryescalier** [comment] 2018-02-17 08:36
Right @mikehenrty the idea is to use pontoon, mention it in the Mozilla forum

One of the requirements is that the website has the option to select other languages.


This is the link with the details

Implementing Pontoon in a Mozilla project
https://developer.mozilla.org/en-US/docs/Mozilla/Implementing_Pontoon_in_a_Mozilla_website

**Comment by geryescalier** [comment] 2018-03-04 11:27
hello @benfrancis does it take help to be able to adapt the website for Potoon? https://developer.mozilla.org/en-US/docs/Mozilla/Implementing_Pontoon_in_a_Mozilla_website I can ask the friends of Mozilla Hispano to help us

**Comment by benfrancis** [comment] 2018-03-06 12:35
Let me look into this a bit further and come up with a design for a language switcher. Proposals in pull requests also welcome!

**Comment by geryescalier** [comment] 2019-11-13 14:59
Hello @benfrancis  a very practical option for the community to support with translations is the way of working of MDN Mozilla https://wiki.developer.mozilla.org/en/docs/MDN/Contribute/Localize/Project:Translating_MDN_pages is a wiki , this format allows communities of different languages to work on translations in a very simple way, this allows greater participation and strengthens the community.

**Comment by benfrancis** [comment] 2019-11-14 12:53
Hi @geryescalier, unfortunately a wiki is not a good fit for our website or the gateway (that link didn't work for me BTW).

We now have a mechanism for localising the gateway, we just need to hook up with Pontoon to manage the contributions.

**Comment by geryescalier** [comment] 2019-11-14 13:01
> Hi @geryescalier, unfortunately a wiki is not a good fit for our website or the gateway (that link didn't work for me BTW).
> 
> We now have a mechanism for localising the gateway, we just need to hook up with Pontoon to manage the contributions.
Good thing to do for Pontoon!
Is there an approximate date so that you can work with Pontoon and be able to perform the translations?

**Comment by benfrancis** [comment] 2019-11-14 13:03
> Is there an approximate date so that you can work with Pontoon and be able to perform the translations?

Not currently, no. We're going to look at this once the 0.10 release is over this week.

**Comment by geryescalier** [comment] 2019-11-14 13:07
> > Is there an approximate date so that you can work with Pontoon and be able to perform the translations?
> 
> Not currently, no. We're going to look at this once the 0.10 release is over this week.

Thank you very much I will be attentive when available, to be able to help with the translations.

**Comment by mrstegeman** [comment] 2019-12-26 20:04
Duplicate of #64.

**Closed by mrstegeman** 2019-12-26 20:04 UTC
